from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d73117498263"
down_revision: str | None = "34fb17391a52"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.execute("CREATE INDEX ON document_store USING hnsw (embedding vector_cosine_ops);")


def downgrade() -> None:
    # The index name is auto-generated by Postgres, so we need to find it first.
    # A safe approach is to just drop it if it exists, but for a clean downgrade,
    # you'd ideally know the name. Assuming a default naming convention is risky.
    # For now, we will assume the default name for dropping.
    # A better practice in production would be to explicitly name the index.
    op.execute("DROP INDEX IF EXISTS ix_document_store_embedding;") 